#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""r25: إضافة ترجمات EN لكل نصوص غلاف Business OS واللوحة والتهيئة الجديدة."""
import json

NEW = {
  # ═══ الغلاف: الشريط الجانبي ═══
  "نظام تشغيل الأعمال": "Business OS",
  "لوحة التحكم": "Dashboard",
  "الفواتير": "Invoices",
  "العملاء": "Customers",
  "المدفوعات": "Payments",
  "التقارير": "Reports",
  "الذكاء الاصطناعي": "AI",
  "المساعد الذكي": "AI Assistant",
  "الاستيراد الذكي": "Smart Import",
  "التحليل الذكي": "Smart Parsing",
  "العمليات": "Operations",
  "المشتريات": "Purchases",
  "الطباعة": "Printing",
  "التذكيرات": "Reminders",
  "الإدارة": "Admin",
  "الشركة": "Company",
  "الموقع": "Website",
  "المستخدمون والأدوار": "Users & Roles",
  "التكاملات": "Integrations",
  "النظام": "System",
  "{0} شركة متاحة": "{0} companies available",
  "الشركة الرئيسية": "Main Company",
  "إضافة شركة جديدة": "Add a new company",
  "باقة الأعمال": "Business Plan",
  "/ شركة / شهرياً": "/ company / month",
  "إدارة الباقة": "Manage Plan",
  "المساعدة": "Help",
  "التوثيق": "Documentation",
  "الدعم": "Support",
  "توسيع الشريط الجانبي": "Expand sidebar",
  "طي الشريط الجانبي": "Collapse sidebar",
  "التنقل الرئيسي": "Main navigation",
  "إغلاق القائمة": "Close menu",
  "تبديل الشركة": "Switch company",

  # ═══ الغلاف: الشريط العلوي ═══
  "ابحث عن أي شيء… فواتير، عملاء، منتجات، مدفوعات": "Search anything… invoices, customers, products, payments",
  "بحث شامل": "Global search",
  "اللغة": "Language",
  "عملة العرض": "Display currency",
  "عملة العرض — عملة الشركة المحاسبية مستقلة": "Display currency — company accounting currency is independent",
  "تُضبط عملة المحاسبة من إعدادات الشركة": "Accounting currency is configured in company settings",
  "الدولة": "Country",
  "تؤثر في صيغة التاريخ والأرقام فقط — بلا مساس بإعدادات الشركة": "Affects date & number formats only — never touches company settings",
  "عالمي (بلا تحديد)": "Global (none)",
  "العالم": "Global",
  "الوضع النهاري": "Light mode",
  "الوضع الليلي": "Dark mode",
  "الإشعارات": "Notifications",
  "مركز التنبيهات": "Alert Center",
  "لا توجد تنبيهات — كل شيء يسير على ما يرام": "No alerts — everything is running smoothly",
  "مدير النظام": "Admin",
  "مشترك": "Subscriber",
  "موظف": "Employee",
  "حسابي": "My Account",
  "تسجيل الخروج": "Log out",

  # ═══ لوحة الأوامر ⌘K ═══
  "البحث الشامل": "Global Search",
  "ابحث… فواتير، عملاء، إجراءات": "Search… invoices, customers, actions",
  "حقل البحث": "Search field",
  "إغلاق": "Close",
  "لا نتائج لـ «{0}»": "No results for “{0}”",
  "تنقل": "navigate",
  "فتح": "open",
  "إجراء سريع": "Quick action",
  "استيراد بيانات (CSV / Excel)": "Import data (CSV / Excel)",

  # ═══ لوحة AI الجانبية ═══
  "لوحة GarfiX AI": "GarfiX AI panel",
  "لوحة المساعد الذكي": "AI assistant panel",
  "إغلاق لوحة الذكاء الاصطناعي": "Close AI panel",
  "اسألني أي شيء أو أعطني مهمة": "Ask me anything or give me a task",

  # ═══ الجوال ═══
  "التنقل السفلي": "Bottom navigation",
  "إجراءات سريعة": "Quick Actions",
  "فتح القائمة الجانبية": "Open sidebar",

  # ═══ رأس اللوحة + المدى ═══
  "صباح الخير": "Good morning",
  "طاب يومك": "Good afternoon",
  "مساء الخير": "Good evening",
  "ليلة سعيدة": "Good night",
  "، {0}": ", {0}",
  "إليك ما يحدث في نشاطك التجاري اليوم.": "Here's what's happening with your business today.",
  "المدى الزمني": "Date range",
  "اليوم": "Today",
  "7 أيام": "7 Days",
  "30 يوماً": "30 Days",
  "3 أشهر": "3 Months",
  "12 شهراً": "12 Months",
  "هذا الشهر": "This Month",
  "الشهر الماضي": "Last Month",
  "مخصص": "Custom",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",

  # ═══ KPI ═══
  "مؤشرات الأداء": "Key metrics",
  "إجمالي الفواتير": "Total Invoices",
  "المدفوع": "Paid",
  "قيد الانتظار": "Pending",
  "متأخر": "Overdue",
  "مقارنة بالفترة السابقة": "vs previous period",
  "{0} في الفترة السابقة": "{0} in the previous period",
  "{0} فاتورة محصّلة": "{0} paid invoices",
  "{0} فاتورة غير مكتملة": "{0} open invoices",
  "{0} فاتورة تجاوزت الاستحقاق": "{0} invoices past due",
  "عدد الفواتير الصادرة خلال المدى المحدد — انقر لعرض القائمة": "Invoices issued in the selected range — click to open the list",
  "المبالغ المحصّلة من فواتير الفترة — انقر لعرض المدفوعة": "Amounts collected from this period's invoices — click to view paid",
  "المتبقي من فواتير الفترة غير المسددة بالكامل": "Remaining balance of this period's unsettled invoices",
  "إجمالي المتبقي من الفواتير المتأخرة عن تاريخ الاستحقاق": "Total remaining on invoices past their due date",
  "اتجاه {0}": "{0} trend",

  # ═══ نظرة الإيرادات ═══
  "نظرة عامة على الإيرادات": "Revenue Overview",
  "مدى الرسم": "Chart range",
  "التجميع": "Grouping",
  "يومي": "Daily",
  "أسبوعي": "Weekly",
  "شهري": "Monthly",
  "إجمالي الإيراد": "Total Revenue",
  "عدد الفواتير": "Number of Invoices",
  "متوسط الفاتورة": "Average Invoice",
  "الإيراد": "Revenue",
  "فواتير": "invoices",

  # ═══ أحدث الفواتير ═══
  "أحدث الفواتير": "Recent Invoices",
  "عرض الكل": "View All",
  "الفاتورة": "Invoice",
  "العميل": "Customer",
  "التاريخ": "Date",
  "المبلغ": "Amount",
  "الحالة": "Status",
  "إجراءات": "Actions",
  "عميل": "Customer",
  "لا توجد فواتير بعد": "No invoices yet",
  "أنشئ فاتورتك الأولى وابدأ بتتبع أعمالك.": "Create your first invoice and start tracking your business.",
  "أنشئ فاتورتك الأولى وابدأ بتتبع أعمالك. أو استورد بياناتك القائمة من CSV / Excel بضغطة واحدة.": "Create your first invoice and start tracking your business — or import your existing data from CSV / Excel in one click.",
  "عرض": "View",
  "تعديل": "Edit",
  "تكرار": "Duplicate",
  "تنزيل PDF": "Download PDF",
  "إرسال تذكير واتساب": "Send WhatsApp reminder",
  "تسجيل دفعة": "Record Payment",
  "✅ فاتورة مكررة — جاهزة للتعديل": "Duplicated invoice — ready to edit",

  # ═══ شارات الحالة ═══
  "مدفوعة": "Paid",
  "جزئي": "Partial",
  "متأخرة": "Overdue",
  "مسودة": "Draft",
  "ملغاة": "Cancelled",

  # ═══ الإجراءات السريعة ═══
  "إنشاء فاتورة": "Create Invoice",
  "فاتورة جديدة في خطوات": "A new invoice in seconds",
  "إضافة عميل": "Add Customer",
  "أضفه لدليل العملاء": "Add them to the directory",
  "حصّل وحدّث الفواتير": "Collect and update invoices",
  "استيراد البيانات": "Import Data",
  "CSV / Excel ذكي": "Smart CSV / Excel",
  "عرض التقارير": "View Reports",
  "تحليلات شاملة": "Full analytics",
  "اسأل GarfiX AI": "Ask GarfiX AI",
  "ذكاء متصل ببياناتك": "AI connected to your data",
  "أنجز أكثر وأسرع مع GarfiX": "Get things done faster with GarfiX",

  # ═══ المدفوعات المستحقة ═══
  "مدفوعات مستحقة": "Outstanding Payments",
  "{0} عميل · إجمالي {1}": "{0} customers · total {1}",
  "تذكير للمحددين": "Remind selected",
  "لا مدفوعات مستحقة": "No outstanding payments",
  "كل الفواتير محصّلة — عمل رائع!": "All invoices are collected — great job!",
  "تحديد الكل": "Select all",
  "تحديد {0}": "Select {0}",
  "أيام التأخير": "Days Overdue",
  "{0} يوم": "{0} days",
  "إرسال تذكير": "Send Reminder",
  "عرض العميل": "View Customer",
  "تُعرض أعلى {0} من {1} عميل": "Showing top {0} of {1} customers",

  # ═══ المبيعات حسب المنتج ═══
  "المبيعات حسب المنتج": "Sales by Product",
  "الإيراد": "Revenue",
  "الكمية": "Quantity",
  "إجمالي المبيعات": "Total Sales",
  "وحدة مباعة": "units sold",
  "لا مبيعات بعد": "No sales yet",
  "ستظهر توزيعة المنتجات هنا مع أول فاتورة.": "Product distribution will appear here with your first invoice.",
  "أخرى": "Others",
  "مخطط دائري": "Donut chart",
  "مخطط مصغّر": "Sparkline",

  # ═══ كبار العملاء ═══
  "كبار العملاء": "Top Customers",
  "الفواتير": "Invoices",
  "المستحق": "Outstanding",
  "فاتورة": "invoice",
  "مستحق": "outstanding",
  "لا عملاء بعد": "No customers yet",
  "أضف عملاءك وابدأ رحلة البيع.": "Add your customers and start selling.",

  # ═══ الحالة العالمية ═══
  "حالة الأعمال العالمية": "Global Business Status",
  "بنية GarfiX العالمية — جاهزة لأي سوق": "GarfiX's global architecture — ready for any market",
  "دولة": "Country",
  "لغة": "Language",
  "عملة": "Currency",
  "أي": "Any",
  "شركة": "Company",
  "مستخدم": "User",
  "196 دولة · 28 لغة · أي عملة": "196 countries · 28 languages · any currency",

  # ═══ مركز التنبيهات ═══
  "{0} تنبيهات تحتاج انتباهك": "{0} alerts need your attention",
  "كل شيء تحت السيطرة": "Everything is under control",
  "لا تنبيهات — أعمالك تسير بسلاسة": "No alerts — your business is running smoothly",
  "{0} فاتورة متأخرة عن الاستحقاق": "{0} invoices overdue",
  "اطّلع وأرسل تذكيرات السداد": "Review and send payment reminders",
  "{0} فواتير حُصّلت اليوم": "{0} invoices paid today",
  "تحصيل يمشي بشكل ممتاز": "Collections are going great",
  "إيراد الشهر ارتفع {0}%": "Monthly revenue increased {0}%",
  "إيراد الشهر انخفض {0}%": "Monthly revenue decreased {0}%",
  "{0} عملاء تجاوزوا حد الائتمان": "{0} customers exceeded their credit limit",
  "توصية GarfiX AI": "GarfiX AI recommendation",
  "راجع مع AI": "Review with AI",
  "ارتفعت مستحقاتك المتأخرة إلى {0}. أنصح بإرسال تذكيرات سداد إلى {1} عملاء اليوم.": "Your overdue receivables rose to {0}. I recommend sending payment reminders to {1} customers today.",

  # ═══ رؤى AI ═══
  "رؤى الذكاء الاصطناعي للأعمال": "AI Business Insights",
  "تحليل لحظي لبياناتك": "Live analysis of your data",
  "ماذا حدث": "What happened",
  "لماذا يهم": "Why it matters",
  "الإجراء الموصى": "Recommended action",
  "الأثر المتوقع": "Expected impact",
  "تنفيذ التوصية": "Apply Recommendation",
  "اسأل AI": "Ask AI",
  "ارتفع الإيراد {0}% هذا الشهر ({1} مقابل {2}).": "Revenue increased {0}% this month ({1} vs {2}).",
  "الإيراد هذا الشهر {0} عبر {1} فاتورة.": "Revenue this month is {0} across {1} invoices.",
  "«{0}» يقود النمو بإيراد {1} — والمتأخرات {2} تضغط على التدفق النقدي.": "“{0}” is driving growth with {1} in revenue — while {2} in overdue balances pressures cash flow.",
  "المتأخرات المتزايدة تضغط على التدفق النقدي.": "Growing overdue balances are pressuring cash flow.",
  "أرسل تذكير سداد اليوم لـ {0} عملاء متأخرين — أبرزهم {1} بمبلغ {2}.": "Send a payment reminder today to {0} overdue customers — the largest being {1} with {2}.",
  "لا إجراء عاجلاً — تابع التحصيل المنتظم.": "No urgent action — keep up regular collections.",
  "استرداد يصل إلى {0} من المستحقات المتأخرة.": "Recover up to {0} of overdue receivables.",

  # ═══ الحالات (تحميل/خطأ) ═══
  "تعذّر تحميل الفواتير": "Unable to load invoices",
  "بياناتك بأمان — حاول مرة أخرى.": "Your data is safe — try again.",
  "حاول مجدداً": "Try Again",
  "جارٍ تحميل لوحة التحكم": "Loading your dashboard",

  # ═══ شاشة المدفوعات ═══
  "المدفوعات والتحصيل": "Payments & Collections",
  "تابع التحصيل والمستحقات وتذكيرات السداد من مكان واحد.": "Track collections, outstanding balances and payment reminders in one place.",
  "المحصّل": "Collected",
  "{0} فاتورة مسددة": "{0} settled invoices",
  "{0} عميل": "{0} customers",
  "{0} عميل متأخر": "{0} overdue customers",
  "إدارة التحصيل": "Collections Management",
  "المستحقات": "Outstanding",
  "المسددة": "Settled",
  "لا فواتير مسددة بعد": "No settled invoices yet",
  "سجّل أول دفعة ليتابع GarfiX تحصيلك.": "Record your first payment and GarfiX will track your collections.",
  "المستحق": "Due",

  # ═══ شاشة التذكيرات ═══
  "تذكيرات سداد واتساب فورية — فردية وجماعية — مع سجل مرجعي لكل عميل.": "Instant WhatsApp payment reminders — individual or bulk — with a reference log for every customer.",
  "تذكير جماعي لكل المتأخرين": "Bulk remind all overdue",
  "متأخرة": "Overdue",
  "قادمة على الاستحقاق": "Upcoming due",
  "غير متأخرة بعد": "not overdue yet",
  "أطول تأخير": "Longest overdue",
  "الفواتير المتأخرة عن الاستحقاق": "Invoices overdue",
  "{0} فاتورة بإجمالي {1}": "{0} invoices totaling {1}",
  "لا فواتير متأخرة": "No overdue invoices",
  "كل المستحقات ضمن مواعيدها — ممتاز!": "All receivables are on schedule — excellent!",
  "{0} فاتورة غير متأخرة بعد": "{0} invoices not overdue yet",
  "الاستحقاق": "Due date",
  "التأخير": "Overdue",
  "المتبقي": "Remaining",
  "عرض الفاتورة": "View invoice",
  "لا فاتورة متبقية لهذا العميل": "No remaining invoice for this customer",

  # ═══ شاشة المساعدة ═══
  "المساعدة والدعم": "Help & Support",
  "GarfiX نظام تشغيل أعمال عالمي: فواتير وعملاء ومدفوعات وتقارير وذكاء اصطناعي — لأي شركة في أي دولة. اختر ما يناسبك:": "GarfiX is a global Business OS: invoices, customers, payments, reports and AI — for any company in any country. Pick what suits you:",
  "أدلة الاستخدام والميزات": "Usage guides and features",
  "الدعم عبر واتساب": "WhatsApp support",
  "رد سريع من فريق GarfiX": "Fast replies from the GarfiX team",
  "إعداد مزوّد الذكاء الاصطناعي": "Configure the AI provider",

  # ═══ التهيئة ═══
  "أساسيات الشركة": "Company Basics",
  "إعدادات الأعمال": "Business Configuration",
  "العملة والضريبة": "Currency & Tax",
  "تجهيز الشركة": "Business Setup",
  "الاكتمال": "Completion",
  "البدء السريع الذكي": "Smart Quick Start",
  "إعداد سريع — أقل من دقيقتين": "Quick setup — under 2 minutes",
  "أنشئ شركتك": "Create Your Company",
  "خطوتان قصيرتان ويكون كل شيء جاهزاً — يمكنك تخطي الباقي وإكماله لاحقاً من الإعدادات.": "Two short steps and you're done — skip the rest and complete it later in settings.",
  "جاهز عالمياً": "Global ready",
  "عملات متعددة": "Multi-currency",
  "مدعوم بالذكاء": "AI powered",
  "آمن ومحمي": "Secure & protected",
  "اسم الشركة (إنجليزي)": "Company name (English)",
  "الاسم العربي (اختياري)": "Arabic name (optional)",
  "نوع النشاط": "Business type",
  "شركة تجارية": "Trading Company",
  "متجر تجزئة": "Retail Store",
  "متجر إلكتروني": "Online Store",
  "خدمات واستشارات": "Services & Consulting",
  "تقنية وبرمجيات": "Technology & Software",
  "مطعم وأغذية": "Restaurant & Food",
  "مقاولات وإنشاءات": "Contracting & Construction",
  "صحة وعناية": "Health & Care",
  "تعليم وتدريب": "Education & Training",
  "أخرى": "Other",
  "رقم الهاتف": "Phone number",
  "لديك حساب بالفعل؟": "Already have an account?",
  "اختر شركة موجودة": "Choose an existing company",
  "استُنبطت هذه الإعدادات ذكياً من دولتك — يمكنك تعديل أي منها الآن أو لاحقاً.": "These settings were smartly inferred from your country — you can adjust any of them now or later.",
  "العملة المحاسبية": "Accounting currency",
  "لغة الفواتير الافتراضية": "Default invoice language",
  "العربية (RTL)": "العربية (RTL)",
  "صيغة التاريخ": "Date format",
  "المنطقة الزمنية": "Time zone",
  "عملة المحاسبة مستقلة عن عملة العرض — كلاهما قابل للتغيير لاحقاً.": "Accounting currency is independent from display currency — both can be changed later.",
  "اختر نظام الضريبة المناسب لدولتك — استُنبط الاقتراح من {0}.": "Choose the tax system that fits your country — suggested from {0}.",
  "بلا ضريبة": "No Tax",
  "لا تُضاف ضريبة": "No tax applied",
  "ضريبة قيمة مضافة": "VAT",
  "ضريبة سلع وخدمات": "GST",
  "ضريبة مبيعات": "Sales Tax",
  "النسبة الافتراضية (٪)": "Default rate (%)",
  "معاينة فاتورة": "Invoice preview",
  "المجموع الفرعي": "Subtotal",
  "الإجمالي": "Total",
  "كل هذا اختياري — أكمله الآن أو لاحقاً من إعدادات الشركة.": "Everything here is optional — complete it now or later in company settings.",
  "شعار الشركة": "Company logo",
  "لون العلامة": "Brand color",
  "البريد الإلكتروني (اختياري)": "Email (optional)",
  "العنوان (اختياري)": "Address (optional)",
  "المدينة — الحي": "City — District",
  "أنشئ شركتي الآن": "Create My Company",
  "جارٍ إنشاء الشركة…": "Creating your company…",
  "تعذّر إنشاء الشركة — حاول مجدداً": "Couldn't create the company — try again",
  "رجوع": "Back",
  "التالي": "Next",
  "أنت جاهز!": "You're All Set!",
  "أُنشئت شركتك بنجاح — أول 100 شركة مجاناً بالكامل. لا حاجة لأي دفع الآن.": "Your company was created successfully — the first 100 companies are entirely free. No payment needed now.",
  "الاسم": "Name",
  "النشاط": "Activity",
  "الضريبة": "Tax",
  "متابعة إلى البدء السريع": "Continue to Quick Start",
  "اختر نقطة البداية — كلها اختيارية.": "Pick your starting point — all optional.",
  "أنشئ فاتورتك الأولى": "Create your first invoice",
  "دقيقة واحدة — عميل ومنتج وسعر": "One minute — a customer, a product and a price",
  "أضف عملاءك": "Add your customers",
  "دليل عملاء عالمي بمحافظات 195 دولة": "A global customer directory with 195 countries' regions",
  "استورد بياناتك": "Import your data",
  "CSV / Excel — فواتير وعملاء": "CSV / Excel — invoices and customers",
  "مساعد متصل ببيانات شركتك": "An assistant connected to your company's data",
  "تخطي والدخول إلى لوحة التحكم": "Skip and go to the dashboard",
  "مجاني لأول 100 شركة": "Free for the first 100 companies",

  # ═══ تنبيهات الشريط ═══
  "GarfiX AI جاهز": "GarfiX AI is ready",
  "اسأل بياناتك ونفّذ الإجراءات بمراجعة بشرية": "Ask your data and execute actions with human review",

  # ═══ تبويبات الجذر (عناوين الصفحة) ═══
  "💳 المدفوعات": "Payments",
  "🔔 التذكيرات": "Reminders",
  "❓ المساعدة": "Help",
}

path = "src/lib/app-dict-en.ts"
src = open(path).read()

added, skipped = 0, 0
lines = []
for k, v in NEW.items():
    kk = json.dumps(k, ensure_ascii=False)
    if kk in src:
        skipped += 1
        continue
    lines.append(f"  {kk}: {json.dumps(v, ensure_ascii=False)},")
    added += 1

assert src.rstrip().endswith("};"), "unexpected dictionary tail"
idx = src.rstrip().rfind("\n};")
out = src[:idx] + "\n" + "\n".join(lines) + src[idx:]
open(path, "w").write(out)
print(f"added {added} entries, skipped {skipped} existing")
